#!/bin/bash
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y net-tools
sudo mkdir -p /home/.checker
sudo chown -R $USER:$USER /home/.checker
cp /tmp/client/checker/* /home/.checker
mkdir -p /home/.checker/responses
